name: Client portal CI

on:
  push:
    branches:
      - "**"

jobs:
  cp:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.19.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.19.x

      - name: Install dependencies
        run: |
          yarn install

      - name: Build
        run: |
          yarn build

      - name: Build docker image
        env:
          BASE_IMAGE: node:12.19.1-slim
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/next' )
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker build -t erxes/erxes-cp:${GITHUB_REF#refs/heads/} -f Dockerfile .
          docker push erxes/erxes-cp:${GITHUB_REF#refs/heads/}